<Project>
  <PropertyGroup>
    <!-- Redirect all build output to .build folder -->
    <BaseOutputPath>$(MSBuildThisFileDirectory).build\$(MSBuildProjectName)\</BaseOutputPath>
    <BaseIntermediateOutputPath>$(MSBuildThisFileDirectory).build\$(MSBuildProjectName)\obj\</BaseIntermediateOutputPath>
  </PropertyGroup>
</Project>
